name: pixel_pet_overlay
description: Mascota virtual con IA y sistema de overlay.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dash_bubble: ^1.0.1
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Asegúrate de crear estas carpetas y poner tus imágenes si quieres usarlas después
  assets:
    - assets/icons/pet_icon.png
    - assets/icons/sleep_icon.png
