name: pixel_pet_ai
description: Mi mascota virtual con IA
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # He actualizado dash_bubble a la versión 2.0.0 como sugiere el error de tu imagen
  dash_bubble: ^2.0.0 
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pixel_normal.gif
    - assets/images/pixel_hambriento.gif
    - assets/images/pixel_triste.gif
    - assets/images/pixel_durmiendo.gif
